#!/bin/bash

parameter=$*
#echo $parameter

make $parameter clean && make $parameter && make $parameter do_upload && make $parameter monitor
#&& make $parameter raw_eeprom 

#Atmega328P @8MHz
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U efuse:w:0xFF:m -U hfuse:w:0xDA:m -U lfuse:w:0xE2:m
#Info efuse 0x07 und 0xFF ist identisch -> -e löscht den Flash!
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U flash:w:optiboot_atmega328_8Mhz_19200baud.hex  -U lock:w:0x0F:m

#Atmega328P @16MHz
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U efuse:w:0x05:m -U hfuse:w:0xDE:m -U lfuse:w:0xFF:m
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U flash:w:optiboot_atmega328.hex  -U lock:w:0x0F:m

#Read Fuses
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U lfuse:r:-:i
#Default:  
	#(E:FF, H:D9, L:62)
	#Device signature = 0x1e950f (probably m328p)

#Bootloader compilieren
#https://github.com/Optiboot/optiboot/wiki/CompilingOptiboot
#make LED=B1 AVR_FREQ=8000000L BAUD_RATE=19200 LED_START_FLASHES=3 atmega328
#avrdude -P /dev/ttyUSB0 -b 19200 -c avrisp -p m328p -v -e -U flash:w:optiboot_atmega328.hex  -U lock:w:0x0F:m
