
## Monitor beenden mit Strg+A danach Strg+X

DEVICE_ID		= 4

#FORCE_MONITOR_PORT	=	1
#MONITOR_PORT				=	net:esp:23
#MONITOR_CMD					=	nc
#MONITOR_PARAMS			=	esp 23
	
MONITOR_PORT				= /dev/ttyUSB0

### Libraries
	ARDUINO_LIBS			+= mySPI myRFM69

### CPPFLAGS
### Flags you might want to set for debugging purpose. Comment to stop.
#	CPPFLAGS					+= -DQUIETMODE_DEFAULT_VALUE=false
#	CPPFLAGS				 	+= -DSTORE_CONFIGURATION
	CPPFLAGS         	+= -DHAS_INFO_POLL -DINFO_POLL_CYCLE_TIME=2040 #[s] >=8 <=2040 (60min)
	CPPFLAGS         	+= -DHAS_POWER_OPTIMIZATIONS
	CPPFLAGS					+= -DAVR_LOWPOWER_DEFAULT_VALUE=true	#set AVR to sleep after startup
	CPPFLAGS				 	+= -DREADVCC_CALIBRATION_CONST=1117637L
#	CPPFLAGS				 	+= -DINFO_POLL_PRESCALER_VCC=1
	
	CPPFLAGS					+= -DHAS_SPI -DHAS_RFM69
	CPPFLAGS					+= -DHAS_RFM69_CMD_TUNNELING=2	#1: Host | 2: Satellite
	CPPFLAGS					+= -DRFM69_CMD_TUNNELING_DEFAULT_VALUE=true -DRFM69_CMD_TUNNELING_HOSTID_DEFAULT_VALUE=1
#	CPPFLAGS					+= -DHAS_RFM69_POWER_ADJUSTABLE -DRFM69_POWER_DEFAULT_VALUE=32	#set output power: 0=min, 31=max (for RFM69W or RFM69CW), 0-31 or 32->51 for RFM69HW
	
	CPPFLAGS					+= -DHAS_RFM69_TXonly #Tunneling needed
	CPPFLAGS					+= -DRFM69_TXonly_DEFAULT_VALUE=true
	
	CPPFLAGS					+= -DRFM69_NO_OTHER_PROTOCOLS -DRFM69_NO_BROADCASTS
#	CPPFLAGS					+= -DHAS_RFM69_LISTENMODE #-DHAS_RFM69_POWER_ADJUSTABLE 
#	CPPFLAGS					+= -DHAS_RFM69_ADC_NOISE_REDUCTION #for continouse ADC sampling functions (turn ADC off during TX)
	
	CPPFLAGS				 += -DHAS_LEDs -DLED_ACTIVITY
	CPPFLAGS				 +=	-DHAS_ADC=7 -DHAS_ADC_7_CALIBRATION_CONST=2093L -DINFO_POLL_PRESCALER_ADC=1

	CPPFLAGS				 += -DHAS_TRIGGER=2 #trigger High
	CPPFLAGS				 += -DTRIGGER_PIN=INTOne
	CPPFLAGS				 += -DTRIGGER_DEBOUNCE_TIME=1000 #[ms] !keeps AVR awake during debouncing time!

