
## Monitor beenden mit Strg+A danach Strg+X

DEVICE_ID		= 1
	
MONITOR_PORT				= /dev/ttyUSB0
#	FORCE_MONITOR_PORT	=	1
#	MONITOR_PORT				=	net:nuc:4000
#	MONITOR_CMD					=	nc
#	MONITOR_PARAMS			=	nuc 4001
	
### Libraries
	ARDUINO_LIBS			+= mySPI myRFM69
	ARDUINO_LIBS			+= TimerOne myIRMP
	#ARDUINO_LIBS			+= myPowerMonitor

### CPPFLAGS
### Flags you might want to set for debugging purpose. Comment to stop.
	CPPFLAGS				 	+=	-DINCLUDE_DEBUG_OUTPUT
#	CPPFLAGS					+= -DQUIETMODE_DEFAULT_VALUE=false
#	CPPFLAGS				 	+= -DSTORE_CONFIGURATION
	CPPFLAGS         	+= -DHAS_INFO_POLL -DINFO_POLL_CYCLE_TIME=10 #[s]  #[s] >=8 <=2040 (8s - 34min)

	#CPPFLAGS				 	+= -DINFO_POLL_PRESCALER_VCC=1
	CPPFLAGS				 	+= -DREADVCC_CALIBRATION_CONST=1119041L
	
	CPPFLAGS					+= -DHAS_SPI -DHAS_RFM69=4
	
#	CPPFLAGS					+= -DHAS_RFM69_SNIFF
	#CPPFLAGS					+= -DHAS_RFM69_ADC_NOISE_REDUCTION
	
	CPPFLAGS				 +=	-DHAS_ADC=6
											#-DINFO_POLL_PRESCALER_ADC=1


	CPPFLAGS				 += -DHAS_BUZZER -DBUZZER_PIN=5 -DBUZZER_FREQUENCE=2.730 -DBUZZER_ON_TIME=500 -DBUZZER_OFF_TIME=50
	
	CPPFLAGS				 += -DHAS_IR_RX 

	#CPPFLAGS				 += -DHAS_POWER_MONITOR_CT -DHAS_POWER_MONITOR_VCC_1 -DHAS_POWER_MONITOR_CT2_1 -DHAS_POWER_MONITOR_CT1_1
	#CPPFLAGS				 += -DHAS_POWER_MONITOR_CT=1  -DHAS_POWER_MONITOR_CT1_2 #nuc mit 270 Ohm Burden Resistor
	#CPPFLAGS				 += -DHAS_POWER_MONITOR_PULSE
	
	
